spring.application.name=SpringSecEx

#spring.security.user.name=amit
#spring.security.user.password=kapila

spring.datasource.url=jdbc:postgresql://localhost:5432/amitkapila
spring.datasource.username=amitkapila
spring.datasource.password=
